## This is an example RAUC system configuration. This file will be installed
## into /etc/rauc/system.conf on your target and describes your system from the
## perspective of the RAUC update service.
##
## Adapt and extend the below configuration to your needs and place it in the
## BSP layer of you project. Create a rauc .bbappend file that adds this file
## to your build:
##
##   FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
##
##   SRC_URI:append := " file://system.conf"
##
## ---
##

[system]
compatible=stm32mpu
bootloader=custom
mountprefix=/usr/local/rauc
max-bundle-download-size=805306368

[keyring]
path=/etc/rauc/ca.cert.pem

[handlers]
post-install=/usr/lib/rauc/post-install.sh
bootloader-custom-backend=/usr/lib/rauc/st-boot-script.sh

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs-b
type=ext4
bootname=B

[slot.fip.0]
device=/dev/disk/by-partlabel/fip-a
type=raw
parent=rootfs.0

[slot.fip.1]
device=/dev/disk/by-partlabel/fip-b
type=raw
parent=rootfs.1

[slot.bootfs.0]
device=/dev/disk/by-partlabel/bootfs
type=ext4
parent=rootfs.0

[slot.bootfs.1]
device=/dev/disk/by-partlabel/bootfs-b
type=ext4
parent=rootfs.1

[slot.vendorfs.0]
device=/dev/disk/by-partlabel/vendorfs
type=ext4
parent=rootfs.0

[slot.vendorfs.1]
device=/dev/disk/by-partlabel/vendorfs-b
type=ext4
parent=rootfs.1
